services:
  bot:
    build: .
    container_name: alex-bot
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    command: python main.py
    depends_on:
      - bd-test

  api:
    build: .
    container_name: alex-api
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    command: uvicorn api.main:api --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - bd-test

  bd-test:
     image: "postgres:latest"
     ports:
       - "5432:5432"
     environment:
       POSTGRES_USER: ${DB_USER}
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_DB: ${DB_NAME}
     volumes:
       - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: